#!/bin/bash
#-------------------------------------------------------------------------------
# dotfiles installation script
#-------------------------------------------------------------------------------

set -e

source install.rc

# Add script and configuration file to the exclude list
EXCLUDE=( install *.old ${EXCLUDE[@]} )

# Help message
# Add this option
# -e FILE  Exclude list file
usage()
{
cat << EOF
usage: $0 [OPTIONS]

This script create symlinks in \$HOME for all files found in this directory.

OPTIONS:
    -u  uninstall dotfiles
    -v  increase verbosity
    -h  show this message and exit
EOF
}

UNINSTALL=0

# Parse command line options
while getopts "uvh" OPTION
do
  case $OPTION in
    u) UNINSTALL=1;;
    v) set -x;;
    h) usage; exit 0;;
    ?) usage; exit 1;;
  esac
done

FILES=`ls`

for exclude in ${EXCLUDE[@]}
do
   FILES=(${FILES[@]/$exclude})
done

for filename in ${FILES[@]}
do
    src=$(readlink -f $(pwd)/$filename)
    dst=$HOME/.$filename

    if [ $UNINSTALL -eq 1 ]; then
      unlink $dst
    else
      [ -L $dst ] && unlink $dst
      [ -a $dst ] && mv $dst ${src}.old
      ln -s $src $dst
    fi
done

