#!/bin/bash
#-------------------------------------------------------------------------------
# dotfiles installation script
#-------------------------------------------------------------------------------

set -e

source install.rc

# Add script and configuration file to the exclude list
NAME=$0
EXCLUDE=( ${NAME##./} install.rc ${EXCLUDE[@]} )

echo ${EXCLUDE[@]}
exit

# Help message
# Add this option
# -e FILE  Exclude list file
usage()
{
cat << EOF
usage: $0 [OPTIONS]

This script create symlinks in \$HOME for all files found in this directory.

OPTIONS:
    -h       Show this message
    -f       Force installation
    -v       Increase verbosity
EOF
}

VERBOSE=0
FORCE=0
FILES=`ls`

# Parse command line options
while getopts "vhfg" OPTION
do
  case $OPTION in
    h) usage; exit 1 ;;
    f) FORCE=1 ;;
    v) VERBOSE=1 ;;
    ?) usage; exit ;;
  esac
done

# Remove in $FILES items from $EXCLUDE
for exclude in ${EXCLUDE[@]}; do
    FILES=`echo $FILES | sed "s/\b$exclude\b//g"`
done

# Installation
for filename in $FILES
do
    src=$(readlink -f $(pwd)/$filename)
    dst=$(readlink -f $HOME/.$filename)

    echo $src "->" $dst

    # if [ -a $dst ]; then
    #     if [ $FORCE -eq 0 ]; then
    #         # show_warning "File exists" $dest
    #         # ask_yesno "Overwrite ?" || continue
    #     fi
    #     echo "Deleting file"
    #     rm -rf $dest
    # fi

    # inform "Creating symlink $src to $dest"
    # ln -s $src $dest
done

